-- MySQL Script generated by MySQL Workbench
-- Wed Feb 16 10:13:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProjetoIntegrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProjetoIntegrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjetoIntegrador` DEFAULT CHARACTER SET utf8 ;
USE `ProjetoIntegrador` ;

-- -----------------------------------------------------
-- Table `ProjetoIntegrador`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoIntegrador`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `pronome` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoIntegrador`.`Postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoIntegrador`.`Postagem` (
  `idPostagem` INT NOT NULL AUTO_INCREMENT,
  `titulo_post` VARCHAR(45) NOT NULL,
  `denuncia` INT NOT NULL,
  `tema_post` VARCHAR(45) NOT NULL,
  `texto_post` VARCHAR(1000) NOT NULL,
  `sensivel` TINYINT NOT NULL,
  `data` DATETIME NOT NULL,
  `fk_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPostagem`),
  INDEX `fk_Postagem_Usuario1_idx` (`fk_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Postagem_Usuario1`
    FOREIGN KEY (`fk_idUsuario`)
    REFERENCES `ProjetoIntegrador`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoIntegrador`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoIntegrador`.`Comentario` (
  `idCom` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `texto` VARCHAR(255) NOT NULL,
  `denuncia` INT NOT NULL,
  `sensivel` TINYINT NOT NULL,
  `fk_idUsuario` INT NOT NULL,
  `fk_idPostagem` INT NOT NULL,
  PRIMARY KEY (`idCom`),
  INDEX `fk_Tema_Usuario_idx` (`fk_idUsuario` ASC) VISIBLE,
  INDEX `fk_Comentarios_Postagem1_idx` (`fk_idPostagem` ASC) VISIBLE,
  CONSTRAINT `fk_Tema_Usuario`
    FOREIGN KEY (`fk_idUsuario`)
    REFERENCES `ProjetoIntegrador`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Postagem1`
    FOREIGN KEY (`fk_idPostagem`)
    REFERENCES `ProjetoIntegrador`.`Postagem` (`idPostagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
